### ISSUE TITLE
Love it, but without the div tags

### ISSUE THREAD

**Issue by jasrandal** [Holi0317/md2bbc-web#1]
Hi, I loved trying the web converter from md to bbc. Is there an option to leave off the div tags? I use a program that doesn't recognize those. Thanks for this!

**Comment by Holi0317** [comment]
This should be a issue with [holi0317/md2bbc.js](https://github.com/Holi0317/md2bbc.js). But whatever.

The problem is that BBCode is a messy place. We do have a standard definition of tags. But the issue is not all BBCode implementer implements all tags. Take an example, gamer.com.tw, which is the base site I build this tool, does not implement `[pre]` tag.

What `[div]` tag does is same as `<p>` tag in terms of HTML, under the implementation I based on.

Could you provide which program you are using? What I really need to know is which tag is the program used for paragraphing.

BTW, thanks for being my first issue reporter :smile:

**Comment by jasrandal** [comment]
Hi, thanks so much for the quick reply. Sorry if I reported this in the
wrong place.

I'm using hubzilla.org at this channel:

http://cats.pm/channel/loran

It has a plugin for markdown, but any edits afterwards scrambles the
bbcode into which it has been converted. Can't really tell you how all
that works behind the scenes since I'm a lowly user and went looking for
some way to write in markdown and convert it into bbcode. I like the
former, find it easier and quicker than the latter.

Thanks again.

## 

James Randal Matheny
http://randalmatheny.com

You said / Você disse:

> This should be a issue with holi0317/md2bbc.js[1]. But whatever.
> 
> The problem is that BBCode is a messy place. We do have a standard definition of tags. But the issue is not all BBCode implementer implements all tags. Take an example, gamer.com.tw, which is the base site I build this tool, does not implement [pre] tag.
> 
> What [div] tag does is same as <p> tag in terms of HTML, under the implementation I based on.
> 
> Could you provide which program you are using? What I really need to know is which tag is the program used for paragraphing.
> 
> BTW, thanks for being my first issue reporter :smile:
> 
> —
> Reply to this email directly or view it on GitHub[2]. 

Links:
1. https://github.com/Holi0317/md2bbc.js
2. https://github.com/Holi0317/md2bbc-web/issues/1#issuecomment-160968192

**Comment by Holi0317** [comment]
Seems that hubzilla uses empty line for separating paragraphs. I will add an option to switch between different separating methods whenever I have time.

**Comment by jasrandal** [comment]
Very kind of you, thanks.

## 

James Randal Matheny
http://cristaos.org
http://randalmatheny.com
http://forthrightpress.com

You said / Você disse:

> Seems that hubzilla uses empty line for separating paragraphs. I will add an option to switch between different separating methods whenever I have time.
> 
> —
> Reply to this email directly or view it on GitHub[1]. 

Links:
1. https://github.com/Holi0317/md2bbc-web/issues/1#issuecomment-160992791

**Comment by Holi0317** [comment]
Just updated it. Added an option for customizing some options, including paragraph tag.
